# Se ocorrer algum contratempo, pode-se inativar o checkout e depois reativá-lo

POST https://sandbox.api.pagseguro.com/checkouts/{checkout_id}inactivate
Authorization: Bearer {{PAGBANK_TOKEN}}
Content-Type: application/json