package com.floriculturamonteiro.floricultura.model.checkoutPagBank.pagamento.enums;

public enum Brands {
    PERSONALCARD,
    UPBRASIL,
    BANESECARD,
    VISA,
    MASTERCARD,
    AMEX,
    DINERS,
    HIPERCARD,
    HIPER,
    AURA,
    CABAL,
    AVISTA,
    PLENOCARD,
    ELO,
    GRANDCARD,
    CARDBAN,
    SOROCRED,
    BRASILCARD,
    VERDECARD,
    JCB,
    MAIS,
    POLICARD,
    VALECARD,
    DISCOVER,
    FORTBRASIL,
}
